import { FEATURES } from '@core/constants';

export enum ErrorsEnum {
  PG_UNIQUE_VIOLATION = '23505',
  INTERNAL_ERROR = 'Something occurred internally. Try again later.',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  SIGN_UP_CONFLICT = 'User was already created.',
  GENERIC_NOT_FOUND_EXCEPTION = 'Requested item was not found in database.',
  GENERIC_CONFLICT_EXCEPTION = 'Conflict occurred while processing request. Item already exists in database.',
  DB_FOREIGN_KEY_VIOLATION = 'The referenced record may not exist or is still in use.',
  DB_SERIALIZATION_FAILURE = 'Transaction serialization failed due to concurrent updates. Please retry.',
  DB_DEADLOCK_DETECTED = 'Deadlock detected. Please retry.',
  DB_INVALID_INPUT = 'Invalid input format.',
  DB_VALUE_TOO_LONG = 'One of the provided values is too long for the database column.',
  DB_CHECK_VIOLATION = 'A database check constraint was violated.',
  DB_LOCK_NOT_AVAILABLE = 'Resource is locked by another transaction. Please retry.',
  DB_TIMEOUT = 'Database operation timed out. Please retry.',
  DB_UNAVAILABLE = 'Server is currently unavailable. Please try again later.',
  DB_GENERIC_ERROR = 'A database error occurred. Please try again later.',
  INVALID_TOKEN_TYPE = 'Invalid token type',
  INVALID_ACCESS_TOKEN = 'Invalid access token',
  INVALID_RESET_TOKEN = 'Invalid reset token.',
  TOO_MANY_REQUESTS = 'The application got too many requests. Please try again later.',
  PASSWORD_RESET_TOKEN_EXPIRED = 'Password reset token has expired. Try to reset one more time.',
  INVALID_REFRESH_TOKEN = 'Invalid refresh token',
  REFRESH_TOKEN_REUSE = 'Refresh token reuse detected',
  ACCESS_TOKEN_REUSE = 'Access token reuse detected',
  NO_ACCESS_TOKEN = 'No access token provided',
  ACCESS_TOKEN_REVOKED = 'Access token revoked',
  ACCESS_TOKEN_EXPIRED = 'Access token expired',
  INVALID_CREDENTIALS = 'Invalid credentials',
  SELF_DELETION_NOT_ALLOWED = 'Self deletion is not allowed',
  RESOURCE_ALREADY_EXISTS = 'Resource already exists',
  PASS_DOES_NOT_MATCH = 'Password does not mach',
  USER_DOES_NO_EXIST = 'User does not exist',
  NEWS_DOES_NO_EXIST = 'News not found',
  IMAGE_DOES_NO_EXIST = 'Image does not exist',
  INCORRECT_IMAGE_PAYLOAD = 'Image must have either tempUrl or id',
  ACCESS_DENIED = 'Access denied! Please login once again.',
  ACCESS_DENIED_NO_REFRESH_TOKEN = 'Access to the resource is denied, No refresh token provided.',
  NO_CONTENT = 'No content was provided',
  NOT_ENOUGH_PERMISSIONS = 'You do not have permission to access this resource.',
  NOT_ENOUGH_PERMISSIONS_OPERATION = 'You do not have permission to perform this operation.',
  VERSION_NOT_FOUND = 'Content version miss match. Try updating again.',
  VERSION_MISMATCH = 'Content version miss match. Try updating again.',
  OPERATION_ERROR = 'Unable to perform operation. Try again later.',
  S3_READ_FAILED = 'Could not read image from S3',
  S3_UPLOAD_FAILED = 'Failed to upload image to S3',
  ALCOHOL_PERCENTAGE_WRONG_DECIMAL_PLACES = 'Alcohol percentage must be a number with up to 1 decimal place',
  ALCOHOL_PERCENTAGE_NON_NEGATIVE = 'Alcohol percentage cannot be negative',
  ALCOHOL_PERCENTAGE_NO_EXCEED = 'Alcohol percentage cannot exceed 100',
  IMAGE_WITHOUT_WIDTH = "Image must contain width in it's metadata",
  IMAGE_NO_DOTS = "The image name should not have any dots in it's name.",
}

export const ERROR_MAP = {
  PG_UNIQUE_VIOLATION: 'PG_UNIQUE_VIOLATION',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SIGN_UP_CONFLICT: 'SIGN_UP_CONFLICT',
  INVALID_TOKEN_TYPE: 'INVALID_TOKEN_TYPE',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  GENERIC_NOT_FOUND_EXCEPTION: 'GENERIC_NOT_FOUND_EXCEPTION',
  GENERIC_CONFLICT_EXCEPTION: 'GENERIC_CONFLICT_EXCEPTION',
  DB_UNIQUE_VIOLATION: 'DB_UNIQUE_VIOLATION',
  DB_FOREIGN_KEY_VIOLATION: 'DB_FOREIGN_KEY_VIOLATION',
  DB_NOT_NULL_VIOLATION: 'DB_NOT_NULL_VIOLATION',
  DB_SERIALIZATION_FAILURE: 'DB_SERIALIZATION_FAILURE',
  DB_DEADLOCK_DETECTED: 'DB_DEADLOCK_DETECTED',
  DB_INVALID_INPUT: 'DB_INVALID_INPUT',
  DB_VALUE_TOO_LONG: 'DB_VALUE_TOO_LONG',
  DB_CHECK_VIOLATION: 'DB_CHECK_VIOLATION',
  DB_LOCK_NOT_AVAILABLE: 'DB_LOCK_NOT_AVAILABLE',
  DB_TIMEOUT: 'DB_TIMEOUT',
  DB_UNAVAILABLE: 'DB_UNAVAILABLE',
  DB_GENERIC_ERROR: 'DB_GENERIC_ERROR',
  SELF_DELETION_NOT_ALLOWED: 'SELF_DELETION_NOT_ALLOWED',
  PASSWORD_RESET_TOKEN_EXPIRED: 'PASSWORD_RESET_TOKEN_EXPIRED',
  ACCESS_TOKEN_REVOKED: 'ACCESS_TOKEN_REVOKED',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  NO_ACCESS_TOKEN: 'NO_ACCESS_TOKEN',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',
  ACCESS_TOKEN_REUSE: 'ACCESS_TOKEN_REUSE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_ID: 'INVALID_ID',
  INVALID_EMAIL: 'INVALID_EMAIL',
  PASS_DOES_NOT_MATCH: 'PASS_DOES_NOT_MATCH',
  USER_DOES_NO_EXIST: 'USER_DOES_NO_EXIST',
  NEWS_DOES_NO_EXIST: 'NEWS_DOES_NO_EXIST',
  IMAGE_DOES_NO_EXIST: 'IMAGE_DOES_NO_EXIST',
  INCORRECT_IMAGE_PAYLOAD: 'INCORRECT_IMAGE_PAYLOAD',
  ACCESS_DENIED: 'ACCESS_DENIED',
  ACCESS_DENIED_NO_REFRESH_TOKEN: 'ACCESS_DENIED_NO_REFRESH_TOKEN',
  NO_CONTENT: 'NO_CONTENT',
  VERSION_NOT_FOUND: 'VERSION_NOT_FOUND',
  VERSION_MISMATCH: 'VERSION_MISMATCH',
  NOT_ENOUGH_PERMISSIONS: 'NOT_ENOUGH_PERMISSIONS',
  NOT_ENOUGH_PERMISSIONS_OPERATION: 'NOT_ENOUGH_PERMISSIONS_OPERATION',
  OPERATION_ERROR: 'OPERATION_ERROR',
  S3_READ_FAILED: 'S3_READ_FAILED',
  S3_UPLOAD_FAILED: 'S3_UPLOAD_FAILED',
  ALCOHOL_PERCENTAGE_WRONG_DECIMAL_PLACES:
    'ALCOHOL_PERCENTAGE_WRONG_DECIMAL_PLACES',
  ALCOHOL_PERCENTAGE_NON_NEGATIVE: 'ALCOHOL_PERCENTAGE_NON_NEGATIVE',
  ALCOHOL_PERCENTAGE_NO_EXCEED: 'ALCOHOL_PERCENTAGE_NO_EXCEED',
  IMAGE_WITHOUT_WIDTH: 'IMAGE_WITHOUT_WIDTH',
  IMAGE_MINIMUM_WIDTH: 'IMAGE_MINIMUM_WIDTH',
  IMAGE_NO_DOTS: 'IMAGE_NO_DOTS',
} as const;

export const ERROR_MESSAGES = {
  notFound: (
    key: string,
    value: string,
    feature: (typeof FEATURES)[keyof typeof FEATURES],
  ) => `${feature} with ${key} ${value} not found`,
  uniqueViolation: (field?: string) =>
    `A record with the same "${field ? field : 'field'}" already exists.`,
  notNullViolation: (column?: string) =>
    `Field "${column ? column : 'column'}" is required. A required field is missing.`,
  imageMinimumWidth: (width: number) =>
    `Please upload an image at least ${width}px wide for best quality`,
};
