import { FEATURES } from '@core/constants';

export enum ErrorsEnum {
  PG_UNIQUE_VIOLATION = '23505',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  SIGN_UP_CONFLICT = 'User was already created.',
  GENERIC_CONFLICT_EXCEPTION = 'Conflict occurred while processing request. Item already exists in database.',
  INVALID_TOKEN_TYPE = 'Invalid token type',
  INVALID_ACCESS_TOKEN = 'Invalid access token',
  INVALID_RESET_TOKEN = 'Invalid reset token.',
  PASSWORD_RESET_TOKEN_EXPIRED = 'Password reset token has expired. Try to reset one more time.',
  INVALID_REFRESH_TOKEN = 'Invalid refresh token',
  REFRESH_TOKEN_REUSE = 'Refresh token reuse detected',
  ACCESS_TOKEN_REUSE = 'Access token reuse detected',
  NO_ACCESS_TOKEN = 'No access token provided',
  ACCESS_TOKEN_REVOKED = 'Access token revoked',
  ACCESS_TOKEN_EXPIRED = 'Access token expired',
  INVALID_CREDENTIALS = 'Invalid credentials',
  PASS_DOES_NOT_MATCH = 'Password does not mach',
  USER_DOES_NO_EXIST = 'User does not exist',
  NEWS_DOES_NO_EXIST = 'News not found',
  IMAGE_DOES_NO_EXIST = 'Image does not exist',
  INCORRECT_IMAGE_PAYLOAD = 'Image must have either tempUrl or id',
  ACCESS_DENIED = 'Access denied! Please login once again.',
  ACCESS_DENIED_NO_REFRESH_TOKEN = 'Access to the resource is denied, No refresh token provided.',
  NO_CONTENT = 'No content was provided',
  NOT_ENOUGH_PERMISSIONS = 'You do not have permission to access this resource.',
  NOT_ENOUGH_PERMISSIONS_OPERATION = 'You do not have permission to perform this operation.',
  VERSION_NOT_FOUND = 'Content version miss match. Try updating again.',
  VERSION_MISMATCH = 'Content version miss match. Try updating again.',
  OPERATION_ERROR = 'Unable to perform operation. Try again later.',
  S3_READ_FAILED = 'Could not read image from S3',
  S3_UPLOAD_FAILED = 'Failed to upload image to S3',
  ALCOHOL_PERCENTAGE_WRONG_DECIMAL_PLACES = 'Alcohol percentage must be a number with up to 1 decimal place',
  ALCOHOL_PERCENTAGE_NON_NEGATIVE = 'Alcohol percentage cannot be negative',
  ALCOHOL_PERCENTAGE_NO_EXCEED = 'Alcohol percentage cannot exceed 100',
}

export const ERROR_MAP = {
  PG_UNIQUE_VIOLATION: 'PG_UNIQUE_VIOLATION',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SIGN_UP_CONFLICT: 'SIGN_UP_CONFLICT',
  INVALID_TOKEN_TYPE: 'INVALID_TOKEN_TYPE',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  GENERIC_CONFLICT_EXCEPTION: 'GENERIC_CONFLICT_EXCEPTION',
  PASSWORD_RESET_TOKEN_EXPIRED: 'PASSWORD_RESET_TOKEN_EXPIRED',
  ACCESS_TOKEN_REVOKED: 'ACCESS_TOKEN_REVOKED',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  NO_ACCESS_TOKEN: 'NO_ACCESS_TOKEN',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',
  ACCESS_TOKEN_REUSE: 'ACCESS_TOKEN_REUSE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_ID: 'INVALID_ID',
  INVALID_EMAIL: 'INVALID_EMAIL',
  PASS_DOES_NOT_MATCH: 'PASS_DOES_NOT_MATCH',
  USER_DOES_NO_EXIST: 'USER_DOES_NO_EXIST',
  NEWS_DOES_NO_EXIST: 'NEWS_DOES_NO_EXIST',
  IMAGE_DOES_NO_EXIST: 'IMAGE_DOES_NO_EXIST',
  INCORRECT_IMAGE_PAYLOAD: 'INCORRECT_IMAGE_PAYLOAD',
  ACCESS_DENIED: 'ACCESS_DENIED',
  ACCESS_DENIED_NO_REFRESH_TOKEN: 'ACCESS_DENIED_NO_REFRESH_TOKEN',
  NO_CONTENT: 'NO_CONTENT',
  VERSION_NOT_FOUND: 'VERSION_NOT_FOUND',
  VERSION_MISMATCH: 'VERSION_MISMATCH',
  NOT_ENOUGH_PERMISSIONS: 'NOT_ENOUGH_PERMISSIONS',
  NOT_ENOUGH_PERMISSIONS_OPERATION: 'NOT_ENOUGH_PERMISSIONS_OPERATION',
  OPERATION_ERROR: 'OPERATION_ERROR',
  S3_READ_FAILED: 'S3_READ_FAILED',
  S3_UPLOAD_FAILED: 'S3_UPLOAD_FAILED',
  ALCOHOL_PERCENTAGE_WRONG_DECIMAL_PLACES:
    'ALCOHOL_PERCENTAGE_WRONG_DECIMAL_PLACES',
  ALCOHOL_PERCENTAGE_NON_NEGATIVE: 'ALCOHOL_PERCENTAGE_NON_NEGATIVE',
  ALCOHOL_PERCENTAGE_NO_EXCEED: 'ALCOHOL_PERCENTAGE_NO_EXCEED',
} as const;

export const ERROR_MESSAGES = {
  notFound: (
    key: string,
    value: string,
    feature: (typeof FEATURES)[keyof typeof FEATURES],
  ) => `${feature} with ${key} ${value} not found`,
};
