export const FEATURES = {
  USER: 'user',
  FILE: 'file',
  CONTACTS: 'contacts',
  AUTHENTICATION: 'authentication',
  NEWS: 'news',
  CAROUSEL: 'carousel',
  PRODUCTS: 'products',
  BRANDS: 'brands',
  COUNTRY: 'country',
  BRAND: 'brand',
  PACKAGING_TYPE: 'packaging_type',
  CATEGORY: 'category',
  PRODUCT: 'product',
  PRODUCT_VARIANT: 'product_variant',
  PRODUCT_COLLECTION: 'product_collection',
} as const;
